export const APP_TEXT_ENGLISH = {
  auth: {
    createAccount: "Create Your Account",
    welcomeBack: "Welcome Back",
    welcomeBackTitle: "Welcome Back!",
    registerNow: "REGISTER NOW",
  },
  location: {
    enableLocation: "Enable Location",
    locationDesc:
      "We need your location to deliver orders accurately and track your route.",
    allowAccess: "Allow Location Access",
    getLocation: "Get My Location",
    locationLabel: "Location",
  },
  profile: {
    name: "Name",
    email: "Email",
    workType: "Work Type",
    bio: "Bio",
    experience: "Experience",
    uploadPhoto: "Upload Profile Photo",
    chooseWorkType: "Choose Work Type",
  },
  professions: {
    tailor: "Tailor",
    plumber: "Plumber",
    electrician: "Electrician",
    carpenter: "Carpenter",
    painter: "Painter",
    maid: "Maid",
    houseKeeper: "House Keeper",
    nursing: "Nursing",
    gardener: "Gardener",
    chakali: "Chakali",
    careTaker: "Care Taker",
    cook: "Cook",
    restRoomCleaner: "Rest Room Cleaner",
  },
  booking: {
    chooseExpert: "Choose an Expert",
    verified: "Verified 🟢",
    book: "BOOK",
    addToFavorites: "ADD TO FAVORITES",
    trackOrder: "Track Order",
    specifiedTime: "ALWAYS ON SPECIFIED TIME",
  },
  home: {
    appIntro:
      "Book trusted, top-rated professionals for any home need in just a few taps.",
    exploreServices:
      "Explore our range of doorstep services below and book your expert today.",
    electricServices: "ELECTRIC SERVICES",
    homeServices: "HOME SERVICES",
    laundryServices: "LAUNDRY SERVICES",
    careTakers: "CARE TAKERS",
  },
  settings: {
    generalSettings: "General Settings",
    displayTheme: "Display Theme",
    light: "Light",
    dark: "Dark",
    systemAutomatic: "System Automatic",
    android: "Android",
    ios: "iOS",
    other: "Other",
  },
  speech: {
    startRecognition: "Start Recognition",
    startWebSpeech: "Start Recognition (Web Speech API)",
    stop: "Stop",
    abort: "Abort",
    interimResults: "Interim Results",
    punctuation: "Punctuation",
    onDevice: "OnDevice Recognition",
    continuous: "Continuous",
    volumeEvents: "Volume events",
    voiceProcessing: "Voice Processing (iOS)",
    getPermissions: "Get permissions",
    requestPermissions: "Request permissions",
    micPermissions: "Get microphone permissions",
    speechPermissions: "Get speech recognizer permissions",
    getState: "Get speech recognizer state",
    callAvailability: "Call isRecognitionAvailable()",
    audioActive: "Set audio session active state",
    persistAudio: "Persist audio recording to filesystem",
    transcribeRecording: "Transcribe the recording",
    transcribeLocal: "Transcribe local en-US audio file",
    transcribing: "Transcribing...",
    transcribeRemote: "Transcribe remote audio file",
  },
  common: {
    requesting: "Requesting...",
    close: "Close",
    modalTitle: "This is a modal",
    goHome: "Go to home screen",
    emptyCart: "Your cart is empty",
  },
};
